name: Auto Farm Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Mỗi ngày vào lúc 00:00

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run bot
      run: |
        python bot.py
